# Generated by Django 4.2 on 2024-04-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_bottom"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="price",
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name="bottom",
            name="price",
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name="footwear",
            name="price",
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name="top",
            name="price",
            field=models.FloatField(default=50),
        ),
    ]
