# Generated by Django 4.2 on 2024-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(default="female", max_length=10),
        ),
    ]
