# Generated by Django 4.2 on 2024-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="acc_images"),
                ),
                ("gender", models.CharField(default="female", max_length=10)),
                ("color", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Footwear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="footwear_images"
                    ),
                ),
                ("gender", models.CharField(default="female", max_length=10)),
                ("color", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
